server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studentSystem?charcterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234

mybatis:
  type-aliases-package: com.xan.entity

